// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using grpcBlazorTest.Server;

namespace grpcBlazorTest.Server.Migrations
{
    [DbContext(typeof(DB))]
    [Migration("20201020165232_InitialAndSeed")]
    partial class InitialAndSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("grpcBlazorTest.Shared.Adresa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Broj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ulica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VlasnikFK")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("VlasnikFK");

                    b.ToTable("Adresas");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            Broj = "1",
                            Ulica = "a",
                            VlasnikFK = "a"
                        },
                        new
                        {
                            ID = -2,
                            Broj = "2",
                            Ulica = "b",
                            VlasnikFK = "a"
                        },
                        new
                        {
                            ID = -3,
                            Broj = "3",
                            Ulica = "c",
                            VlasnikFK = "a"
                        },
                        new
                        {
                            ID = -4,
                            Broj = "4",
                            Ulica = "d",
                            VlasnikFK = "b"
                        },
                        new
                        {
                            ID = -5,
                            Broj = "5",
                            Ulica = "e",
                            VlasnikFK = "c"
                        },
                        new
                        {
                            ID = -6,
                            Broj = "6",
                            Ulica = "f",
                            VlasnikFK = "c"
                        },
                        new
                        {
                            ID = -7,
                            Broj = "7",
                            Ulica = "g",
                            VlasnikFK = "d"
                        },
                        new
                        {
                            ID = -8,
                            Broj = "8",
                            Ulica = "h",
                            VlasnikFK = "d"
                        });
                });

            modelBuilder.Entity("grpcBlazorTest.Shared.Korisnik", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Korisniks");

                    b.HasData(
                        new
                        {
                            ID = "a",
                            Ime = "Pera",
                            Prezime = "Peric"
                        },
                        new
                        {
                            ID = "b",
                            Ime = "Neko",
                            Prezime = "Nekic"
                        },
                        new
                        {
                            ID = "c",
                            Ime = "Trecko",
                            Prezime = "Treckovic"
                        },
                        new
                        {
                            ID = "d",
                            Ime = "Bla",
                            Prezime = "BlaBla"
                        });
                });

            modelBuilder.Entity("grpcBlazorTest.Shared.Adresa", b =>
                {
                    b.HasOne("grpcBlazorTest.Shared.Korisnik", "Vlasnik")
                        .WithMany("Adrese")
                        .HasForeignKey("VlasnikFK");
                });
#pragma warning restore 612, 618
        }
    }
}
